apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-counter
spec:
  rules:
    - host: {{ required "Required configuration of .Values.host" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-counter
                port:
                  number: 80
