apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    project: counter
spec:
  serviceName: redis
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      project: counter
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        release: {{ .Release.Name }}
        project: counter
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 30m
              memory: 50Mi
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-redis
