apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
  labels:
    project: counter
spec:
  ports:
    - port: 6379
  selector:
    release: {{ .Release.Name }}
    project: counter
    app: redis
